### ISSUE TITLE
Use of text field for url 

### ISSUE THREAD

**Issue by eskhool** [feincms/feincms3-example#3]
@matthiask, since feincms3 seems to be postgres bound (which is fine by me), it would also be useful to just use a TextField instead of Charfield with a max length of 1000 for the URL.

This would be equally performant, is backward compatible (causing a simple migration) and is future proof for special use cases with longer URLs.

Thoughts?

**Comment by matthiask** [comment]
Hi @eskhool 

Good point. In practice the max. URL length as implemented in various client libraries seems to be 2083 chars. That's really long, and I can't remember seing beautiful URLs longer than ~300 chars.

The only problem I see with TextField is that the default widget is a Textarea (which allows newlines), and I fear that this miscommunicates what the path field is all about. What about simply increasing the path field max_length to an insane number (for example 2000 or even 4000?). This should be [equally performant as a textfield](https://www.postgresql.org/docs/9.0/static/datatype-character.html), and use the (in my opinion) correct widget automatically.

**Comment by eskhool** [comment]
True, no right answers here. I haven't run into a requirement larger than 1000 myself but it just seems ugly (in my opinion ;) to have any length especially when using postgresql which lets you avoid having to put an unnecessary length constraint in the first place. In fact that link mentions a few extra cpu cycles in length constrained fields anyways but that probably does not matter. 

We can also manually specify a TextInput widget with a Text field since I concur that is the right widget to show.

**Comment by matthiask** [comment]
`TextInput` widget: Yes, of course. Currently we don't ship a `PageAdmin` class and I really like this fact, so I think that the case for switching to  `TextField` is not strong enough right now. 

I'd still really appreciate (and merge) a pull request for increasing `max_length` in feincms3 if you want to do this? I'm probably not going to make the change myself, but go for it!

**Comment by eskhool** [comment]
The max_length is not much of an issue. will send a PR along if it becomes one. 

I will give you more feedback as an enduser of feincms3 when we finish integrating it into our app which should be by end next week

**Comment by matthiask** [comment]
Yay, looking forward to this! Thanks in advance :)
