### ISSUE TITLE
http://127.0.0.1:8000/ returns 404 

### ISSUE THREAD

**Issue by lchen198** [feincms/feincms3-example#9]
When I visit the "http://127.0.0.1:8000/" as instructed in the README file, I got a 404 page error. This seems to be a bad experience even for this example project.  I thought the example project didn't work for some reasons. 

It would be nice to redirect user to http://127.0.0.1:8000/en/blog by default or update the README to make it clear which url  works.

```
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Using the URLconf defined in urlconf_fc79ac47a9d92a54518de50d1949dedb, Django tried these URL patterns, in this order:

^de/blog/
^de/veroffentlichungen/
^en/blog/
^en/publications/
admin/
^media/(?P<path>.*)$
The empty path didn’t match any of these.
```

**Comment by matthiask** [comment]
Hi @lchen198 

Thanks for the report and sorry for the late response, I have been on holidays.

I have fixed the issue, `/` now (again) works as it should.
